### ISSUE TITLE
firefox-89-styling-proton-ui.html: fix attention notification for pinned tabs

### ISSUE THREAD

**Issue by rohieb** [jscher2000/userchrome-dot-org#9]
Hi! I used the tab restyler on your page to configure a CSS with tabs connected to the toolbar and compact height. Thanks a lot for that convenient generator! 🙂 However, I noticed when using the generated `userChrome.css` that the blue attention indicator (e.g. for new messages on social media sites in inactive, pinned tabs) now sat directly below the favicon, and was even covered by the non-transparent areas of it. So after a while of fiddling I came up with the following snippet in my `userChrome.css`:

``` css
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"])
{
  background-image: radial-gradient(circle, #00feff 33%, #00c8d7 66%, transparent) !important;
  background-position: center bottom var(--tabs-navbar-shadow-size) !important;
  background-size: 7px 6px !important;
}
```

For reference, here is the original style (I'm still on Firefox 91 ESR):

``` css
.tabbrowser-tab:is([image], [pinned]) > .tab-stack > .tab-content[attention]:not([selected="true"]),
.tabbrowser-tab > .tab-stack > .tab-content[pinned][titlechanged]:not([selected="true"]),
#firefox-view-button[attention] {
  background-image: radial-gradient(circle, var(--tab-attention-icon-color), var(--tab-attention-icon-color) 2px, transparent 2px);
  background-position: center bottom calc(6.5px + var(--tabs-navbar-shadow-size));
  background-size: 4px 4px;
  background-repeat: no-repeat;
}
```

I think the `background-position` could be included when selecting the "Compact height" option in the tab configurator to make the default dot more visible. I also brought back the old "LED-style" indicator, which I emulated with the radial gradient in the `background-image` option. I think this could make another good addition to the configurator, although I don't know how it would conflict with the "Container line at the bottom" setting…

Screenshots of the default style in Firefox 91 (Edit: tested it in Firefox 102 too, works the same):
![b11065ea-5e28-11ed-9973-507b9d024c54](https://user-images.githubusercontent.com/192014/200200720-93aed870-ed40-423a-897b-561212c73858.png)
(in the first tab, the indicator is swallowed completely by the favicon 😕)

With the default style, but changing the `background-position` setting:
![d3ff35f8-5e29-11ed-a46d-507b9d024c54](https://user-images.githubusercontent.com/192014/200201010-212b0048-754c-496a-a4a2-c3d60f8a3314.png)

And with the full `userChrome.css` snippet from above:
![a2723ebe-5e28-11ed-af54-507b9d024c54](https://user-images.githubusercontent.com/192014/200200723-d6d56b63-cb0d-4190-b65f-d50091143045.png)
